//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maj_Adv
    {
        public string maj_code { get; set; }
        public string adv_code { get; set; }
        public string Maj_Adv_level { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual Major Major { get; set; }
    }
}
