//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Std_Act
    {
        public string std_code { get; set; }
        public string act_code { get; set; }
        public Nullable<decimal> Std_Act_num { get; set; }
        public Nullable<System.DateTime> Std_Act_joined { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Student Student { get; set; }
    }
}
